## Hypothesen
Nullhypothese (H0): „Der Preis für einen Gebrauchtwagen ist nicht vom Hersteller abhängig“

Alternativhypothese (H1): „Der Preis für einen Gebrauchtwagen ist vom Hersteller abhängig“

In [47]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [48]:
uc_mercedes = pd.read_csv("mercedes.csv")
uc_hyundai = pd.read_csv("hyundai.csv")

In [49]:
uc_mercedes.describe()

,year,price,mileage,tax,mpg,engineSize
count,13119.000000,13119.000000,13119.000000,13119.000000,13119.000000,13119.000000
mean,2017.296288,24698.596920,21949.559037,129.972178,55.155843,2.071530
std,2.224709,11842.675542,21176.512267,65.260286,15.220082,0.572426
min,1970.000000,650.000000,1.000000,0.000000,1.100000,0.000000
25%,2016.000000,17450.000000,6097.500000,125.000000,45.600000,1.800000
50%,2018.000000,22480.000000,15189.000000,145.000000,56.500000,2.000000
75%,2019.000000,28980.000000,31779.500000,145.000000,64.200000,2.100000
max,2020.000000,159999.000000,259000.000000,580.000000,217.300000,6.200000

In [50]:
uc_hyundai.describe()

,year,price,mileage,tax(£),mpg,engineSize
count,4860.000000,4860.00000,4860.000000,4860.000000,4860.000000,4860.000000
mean,2017.107613,12750.13107,21486.049588,121.147119,53.827798,1.457922
std,1.920456,5992.92231,17710.196964,58.003289,12.736042,0.400788
min,2000.000000,1200.00000,1.000000,0.000000,1.100000,0.000000
25%,2016.000000,8000.00000,8339.250000,125.000000,44.800000,1.200000
50%,2017.000000,11990.00000,17462.000000,145.000000,55.400000,1.600000
75%,2019.000000,15733.75000,30967.000000,145.000000,60.100000,1.700000
max,2020.000000,92000.00000,138000.000000,555.000000,256.800000,2.900000

## Kolmogorov-Smirnov-Test (KS-Test)
ist ein nichtparametrischer Test, der verwendet wird, um zu prüfen, ob zwei Stichproben aus der gleichen Verteilung stammen oder ob eine Stichprobe einer bestimmten Verteilung folgt. Es gibt zwei Hauptvarianten des Tests:

Einseitiger KS-Test: Um zu testen, ob eine Stichprobe einer bestimmten Verteilung folgt.

Zweiseitiger KS-Test: Um zu prüfen, ob zwei Stichproben aus derselben Verteilung stammen.

In Python kannst du den Kolmogorov-Smirnov-Test mit der Bibliothek scipy durchführen. Hier zeige ich dir, wie du beide Varianten des Tests durchführen kannst.

Der Kolmogorov-Smirnov-Test (KS-Test) wird verwendet, um zu testen, ob eine Stichprobe einer bestimmten Verteilung folgt oder um zwei Stichproben zu vergleichen. In Python kann dieser Test mit der Funktion ks_2samp() aus dem Modul scipy.stats für den Vergleich zweier Stichproben oder kstest() für den Vergleich einer Stichprobe mit einer theoretischen Verteilung durchgeführt werden.

Hier ein einfaches Beispiel für den Kolmogorov-Smirnov-Test in Python, sowohl für den Vergleich zweier Stichproben als auch für den Vergleich einer Stichprobe mit einer Normalverteilung.

## Test auf Unabhängigkeit

In [51]:
# Vergleich zweier Stichproben
import numpy as np
from scipy.stats import ks_2samp

# Zwei Stichproben
sample1 = uc_hyundai['price']
sample2 = uc_mercedes['price']

# Kolmogorov-Smirnov-Test für den Vergleich der beiden Stichproben
statistic, p_value = ks_2samp(sample1, sample2)

print(f"KS-Statistik: {statistic}")
print(f"P-Wert: {p_value}")

# Wenn p < 0.05, lehnen wir die Nullhypothese ab
if p_value < 0.05:
    print("Es gibt einen signifikanten Unterschied zwischen den beiden Stichproben. Die stichproben sind unabhängig")
else:
    print("Es gibt keinen signifikanten Unterschied zwischen den beiden Stichproben. Die stichproben sind unabhängig")

KS-Statistik: 0.5911772483411581
P-Wert: 0.0
Es gibt einen signifikanten Unterschied zwischen den beiden Stichproben. Die stichproben sind unabhängig

stats.ks_2samp(data1, data2): Führt den Kolmogorov-Smirnov-Test durch, um zu prüfen, ob data1 und data2 aus der gleichen Verteilung stammen.

ks_stat: Die KS-Statistik misst die größte Differenz zwischen den empirischen Verteilungsfunktionen der beiden Stichproben.

p_value: Der p-Wert des Tests. Wenn dieser kleiner als das Signifikanzniveau ist, lehnt man die Nullhypothese ab und schließt, dass die beiden Stichproben nicht aus der gleichen Verteilung stammen.

Interpretation des p-Werts
Ein kleiner p-Wert (typischerweise kleiner als 0,05) weist darauf hin, dass die Nullhypothese abgelehnt werden kann. Das bedeutet, dass die Daten nicht der angenommenen Verteilung entsprechen (im Fall des Tests für eine Stichprobe) oder dass die beiden Stichproben unterschiedliche Verteilungen haben (im Fall des Tests für zwei Stichproben).

Ein großer p-Wert bedeutet, dass es keine ausreichenden Beweise gibt, die Nullhypothese abzulehnen.

## Test auf Normaltverteilung

### Vergleich einer Stichprobe mit einer theoretischen Normalverteilung:

In [52]:
import numpy as np
from scipy.stats import kstest

# Stichprobe
sample = uc_hyundai['price']

# Kolmogorov-Smirnov-Test für den Vergleich der Stichprobe mit einer Normalverteilung
#statistic, p_value = kstest(sample, 'norm')
ks_stat, p_value = kstest(uc_hyundai['price'], 'norm', args=(np.mean(uc_hyundai['price']), np.std(uc_hyundai['price'])))

print(f"KS-Statistik: {statistic}")
print(f"P-Wert: {p_value}")

# Wenn p < 0.05, lehnen wir die Nullhypothese ab
if p_value < 0.05:
    print("Die Stichprobe weicht signifikant von einer Normalverteilung ab.")
else:
    print("Die Stichprobe folgt einer Normalverteilung.")

KS-Statistik: 0.5911772483411581
P-Wert: 8.578785117132835e-34
Die Stichprobe weicht signifikant von einer Normalverteilung ab.

In [53]:
import numpy as np
from scipy.stats import kstest

# Stichprobe
sample = uc_mercedes['price']

# Kolmogorov-Smirnov-Test für den Vergleich der Stichprobe mit einer Normalverteilung
#statistic, p_value = kstest(sample, 'norm')
ks_stat, p_value = kstest(uc_mercedes['price'], 'norm', args=(np.mean(uc_mercedes['price']), np.std(uc_mercedes['price'])))

print(f"KS-Statistik: {statistic}")
print(f"P-Wert: {p_value}")

# Wenn p < 0.05, lehnen wir die Nullhypothese ab
if p_value < 0.05:
    print("Die Stichprobe weicht signifikant von einer Normalverteilung ab.")
else:
    print("Die Stichprobe folgt einer Normalverteilung.")

KS-Statistik: 0.5911772483411581
P-Wert: 7.747937105606737e-176
Die Stichprobe weicht signifikant von einer Normalverteilung ab.

Erklärung:
stats.kstest(data, 'norm'): Führt den Kolmogorov-Smirnov-Test durch, um zu prüfen, ob die Daten einer Normalverteilung folgen. Der zweite Parameter 'norm' bezeichnet die Normalverteilung.

ks_stat: Die KS-Statistik misst die größte Differenz zwischen der empirischen Verteilungsfunktion der Daten und der theoretischen Verteilung.

p_value: Der p-Wert des Tests. Wenn dieser Wert kleiner als ein Signifikanzniveau (z. B. 0,05) ist, lehnt man die Nullhypothese ab und schließt, dass die Stichprobe nicht der theoretischen Verteilung folgt.

## Der Mann-Whitney-U-Test (auch als Wilcoxon-Rangsummentest bekannt) 
ist ein nicht-parametrischer Test, der verwendet wird, um zu überprüfen, ob zwei unabhängige Stichproben aus der gleichen Verteilung stammen, ohne die Annahme zu machen, dass die Daten einer bestimmten Verteilung folgen.

In Python kann der Mann-Whitney-U-Test mit der Funktion mannwhitneyu() aus dem Modul scipy.stats durchgeführt werden.

Hier ist ein Beispiel, wie man den Mann-Whitney-U-Test in Python durchführt:

In [54]:
import numpy as np
from scipy.stats import mannwhitneyu

# Zwei unabhängige Stichproben
ssample1 = uc_hyundai['price']
sample2 = uc_mercedes['price']

# Mann-Whitney-U-Test durchführen
statistic, p_value = mannwhitneyu(sample1, sample2)

print(f"U-Statistik: {statistic}")
print(f"P-Wert: {p_value}")

# Wenn p < 0.05, lehnen wir die Nullhypothese ab
if p_value < 0.05:
    print("Es gibt einen signifikanten Unterschied zwischen den beiden Stichproben.")
else:
    print("Es gibt keinen signifikanten Unterschied zwischen den beiden Stichproben.")

U-Statistik: 8548412.0
P-Wert: 0.0
Es gibt einen signifikanten Unterschied zwischen den beiden Stichproben.

mannwhitneyu(sample1, sample2): Diese Funktion führt den Mann-Whitney-U-Test durch und vergleicht zwei unabhängige Stichproben. Sie gibt die U-Statistik und den p-Wert zurück.

Die Nullhypothese des Tests lautet, dass es keinen signifikanten Unterschied zwischen den beiden Stichproben gibt, d. h., sie stammen aus der gleichen Verteilung.

Wenn der p-Wert kleiner als 0,05 ist, lehnen wir die Nullhypothese ab und schließen, dass es einen signifikanten Unterschied zwischen den beiden Stichproben gibt.

## T-test für unabhängige Stichproben

Ein t-Test für unabhängige Stichproben wird verwendet, um zu testen, ob es einen signifikanten Unterschied zwischen den Mittelwerten von zwei unabhängigen Gruppen gibt. Dieser Test setzt voraus, dass die beiden Gruppen normal verteilt sind und die Varianzen der beiden Gruppen gleich sind (Homogenität der Varianzen).

In Python kannst du den t-Test für unabhängige Stichproben mit der Funktion ttest_ind() aus dem scipy.stats-Modul durchführen.

In [55]:
import numpy as np
from scipy import stats

# Beispiel-Daten für zwei unabhängige Gruppen
gruppe_1 = uc_hyundai['price']
gruppe_2 = uc_mercedes['price']

# Führe den t-Test durch
t_stat, p_value = stats.ttest_ind(gruppe_1, gruppe_2)
#t_stat, p_value = stats.ttest_ind(gruppe_1, gruppe_2, equal_var=False)

# Ausgabe der Ergebnisse
print(f"T-Wert: {t_stat}")
print(f"P-Wert: {p_value}")

# Interpretation des p-Werts
alpha = 0.05  # Signifikanzniveau
if p_value < alpha:
    print("Die Nullhypothese wird abgelehnt. Es gibt einen signifikanten Unterschied zwischen den Gruppen.")
else:
    print("Die Nullhypothese wird nicht abgelehnt. Es gibt keinen signifikanten Unterschied zwischen den Gruppen.")

T-Wert: -67.21940857133939
P-Wert: 0.0
Die Nullhypothese wird abgelehnt. Es gibt einen signifikanten Unterschied zwischen den Gruppen.

### Erklärung:
stats.ttest_ind(gruppe_1, gruppe_2): Diese Funktion berechnet den t-Wert und den p-Wert für den t-Test der unabhängigen Stichproben.

t-Wert: Ein Maß für die Größe des Unterschieds zwischen den Mittelwerten der beiden Gruppen relativ zur Streuung innerhalb der Gruppen.

p-Wert: Der p-Wert gibt an, ob der Unterschied zwischen den Mittelwerten statistisch signifikant ist. Wenn der p-Wert kleiner als das Signifikanzniveau (typischerweise 0.05) ist, kannst du die Nullhypothese ablehnen und davon ausgehen, dass ein signifikanter Unterschied besteht.

Alpha (α): Das Signifikanzniveau (häufig 0.05) ist die Grenze, unterhalb derer der p-Wert als statistisch signifikant betrachtet wird.

### Voraussetzungen:
Normalverteilung: Der t-Test geht davon aus, dass beide Gruppen normal verteilt sind. Für kleine Stichprobengrößen kannst du einen Normalitätstest wie den Shapiro-Wilk-Test verwenden.

Homogenität der Varianzen: Der t-Test geht davon aus, dass die Varianzen der beiden Gruppen gleich sind.

Die Homogenität der Varianzen ist eine Annahme für den t-Test für unabhängige Stichproben, die besagt, dass die Varianzen der beiden Gruppen, die verglichen werden, gleich sind. Wenn diese Annahme verletzt wird, kann der t-Test möglicherweise fehlerhafte Ergebnisse liefern.

Eine gängige Methode, um die Homogenität der Varianzen zu testen, ist der Levene-Test. Dieser Test prüft, ob die Varianzen zweier oder mehrerer Gruppen signifikant unterschiedlich sind. Der Levene-Test ist robuster gegenüber Abweichungen von der Normalverteilung im Vergleich zum traditionellen F-Test.

In Python kannst du den Levene-Test mit der Funktion levene() aus dem Modul scipy.stats durchführen.

Levene-Test durchführen: Verwende scipy.stats.levene(), um zu prüfen, ob die Varianzen der Gruppen gleich sind.

Ergebnisse interpretieren: Der p-Wert des Tests hilft dir, die Nullhypothese zu überprüfen, die besagt, dass die Varianzen gleich sind.
stats.levene(gruppe_1, gruppe_2): Diese Funktion führt den Levene-Test durch und gibt die Teststatistik und den p-Wert zurück.
Die Nullhypothese des Levene-Tests besagt, dass die Varianzen gleich sind.
Der p-Wert gibt an, ob es genug Beweise gibt, um die Nullhypothese abzulehnen (also ob die Varianzen unterschiedlich sind).

Interpretation:
Wenn der p-Wert kleiner als das Signifikanzniveau (z.B. 0.05) ist, lehnen wir die Nullhypothese ab und schließen, dass die Varianzen der beiden Gruppen unterschiedlich sind.
Wenn der p-Wert größer als 0.05 ist, gibt es keinen signifikanten Unterschied zwischen den Varianzen, und du kannst die Annahme der Homogenität der Varianzen beibehalten.

In [56]:
import numpy as np
from scipy import stats

# Beispiel-Daten für zwei Gruppen
gruppe_1 = uc_hyundai['price']
gruppe_2 = uc_mercedes['price']

# Führe den Levene-Test zur Prüfung der Homogenität der Varianzen durch
stat, p_value = stats.levene(gruppe_1, gruppe_2)

# Ausgabe der Ergebnisse
print(f"Levene-Test Statistik: {stat}")
print(f"P-Wert: {p_value}")

# Interpretation des p-Werts
alpha = 0.05  # Signifikanzniveau
if p_value < alpha:
    print("Die Nullhypothese wird abgelehnt. Die Varianzen der Gruppen sind unterschiedlich.")
else:
    print("Die Nullhypothese wird nicht abgelehnt. Es gibt keine Hinweise auf unterschiedliche Varianzen.")

Levene-Test Statistik: 611.4945770359005
P-Wert: 8.696583072166145e-133
Die Nullhypothese wird abgelehnt. Die Varianzen der Gruppen sind unterschiedlich.

Wenn die Varianzen unterschiedlich sind, kannst du den Welch-T-Test verwenden, der eine Anpassung für ungleiche Varianzen vornimmt.

Für den Welch-T-Test kannst du ttest_ind() mit dem Argument equal_var=False verwenden:

In [57]:
t_stat, p_value = stats.ttest_ind(gruppe_1, gruppe_2, equal_var=False)

In [61]:
#Mann & Whitney Test

import numpy as np
from scipy import stats

# Beispiel-Daten für zwei Gruppen
gruppe_1 = uc_hyundai['price']
gruppe_2 = uc_mercedes['price']

# Führe den U-Test durch
stat, p_value = stats.mannwhitneyu(gruppe_1, gruppe_2)

# Ausgabe der Ergebnisse
print(f"U-Test: {stat}")
print(f"P-Wert: {p_value}")

# Interpretation des p-Werts
alpha = 0.05  # Signifikanzniveau
if p_value < alpha:
    print("Die Nullhypothese wird abgelehnt.")
else:
    print("Die Nullhypothese wird nicht abgelehnt.")

U-Test: 8548412.0
P-Wert: 0.0
Die Nullhypothese wird abgelehnt.